# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# [character]
# format = '[ï“ƒ ó°…‚ ]($style)'
# success_symbol = '[ï“ƒ ó°…‚ ]($style)'
# error_symbol = '[ï“ƒ ó°…‚ ]($style)'
# vimcmd_symbol = '[ï“ƒ ó°…‚ ]($style)'

[git_branch]
symbol = 'ï˜ '

[nodejs]
format = '[î´  $version]($style)'

[deno]
format = '[ğŸ¦–  $version]($style)'

[lua]
format = '[$ó°¢±  version]($style)'

[package]
format = '[$symbol$version]($style) '
symbol = 'î¬© '

[directory]
truncate_to_repo = false
home_symbol = 'ï“¢ '

[directory.substitutions]
'Downloads' = ' ó°‰ '
'Documents' = ' ó±§¶ '
'Music' = ' ó±™ '
'Pictures' = ' ó°‰” '
'Movies' = ' ó°•§ '
'Repos/work/@components/storybook' = ' components'
'Repos/work/kiwi-tokens' = ' tokens'
'Repos/work/sd-internal-transforms' = ' transforms'

